# Selvage 평가 에이전트 설정
agent_model: "gemini-2.5-pro"

evaluation:
  output_dir: "./selvage-eval-results"
  auto_session_id: true  # 자동 생성: eval_20240120_143022_abc123
  
target_repositories:
  - name: cline
    path: /Users/demin_coder/Dev/cline
    tech_stack: typescript
    description: "typescript로 구현된 coding assistant"
    access_mode: readonly  # 읽기 전용 접근
    filter_overrides:
      min_changed_lines: 30
      
  - name: selvage-deprecated
    path: /Users/demin_coder/Dev/selvage-deprecated
    tech_stack: python
    description: "LLM 기반 코드 리뷰 도구 selvage 이전 버전 commit history"
    access_mode: readonly  # 읽기 전용 접근
    filter_overrides:
      min_changed_lines: 50
      
  - name: ecommerce-microservices
    path: /Users/demin_coder/Dev/ecommerce-microservices
    tech_stack: java_spring
    description: "java, spring, jpa로 구현된 MSA 서버 애플리케이션"
    access_mode: readonly  # 읽기 전용 접근
    filter_overrides:
      min_changed_lines: 100
      
  - name: kotlin-realworld
    path: /Users/demin_coder/Dev/kotlin-realworld
    tech_stack: kotlin_jpa
    description: "java, kotlin, jpa로 구현된 호텔 예약 서버 애플리케이션"
    access_mode: readonly  # 읽기 전용 접근
    filter_overrides:
      min_changed_lines: 80

review_models:
  - "gemini-2.5-pro"
  - "gemini-2.5-flash"
  - "o3"
  - "o4-mini-high"
  # - "claude-sonnet-4-thinking"
  - "claude-sonnet-4"

commit_filters:
  stats:
    min_files: 2
    max_files: 10
    min_lines: 50
  merge_handling:
    fast_forward: exclude
    conflict_resolution: include
    squash_merge: include
    feature_branch: conditional  # 변경량 기준
commits_per_repo: 20

workflow:
  skip_existing:
    commit_filtering: true  # 필터링된 commit JSON 존재 시 skip
    review_results: true    # 동일 commit-model 조합 결과 존재 시 skip
  parallel_execution:
    max_concurrent_repos: 2
    max_concurrent_models: 3
  cache_enabled: true

# Selvage 실행 설정
selvage:
  binary_path: "/Users/demin_coder/.local/bin/selvage"
  timeout_seconds: 300
  
