# Selvage 평가 에이전트 설정
agent_model: "gemini-2.5-flash"

evaluation:
  output_dir: "./selvage-eval-results"
  auto_session_id: true  # 자동 생성: eval_20240120_143022_abc123
  
target_repositories:
  - name: cline
    path: /Users/demin_coder/Dev/cline
    tech_stack: typescript
    description: "typescript로 구현된 coding assistant"
    filter_overrides:
      min_changed_lines: 30  # TS는 더 작은 단위 변경 허용
      file_types: [".ts", ".tsx", ".js", ".jsx"]
      
  - name: selvage-deprecated
    path: /Users/demin_coder/Dev/selvage-deprecated
    tech_stack: mixed
    description: "selvage 이전 버전 commit history"
    access_mode: readonly  # 읽기 전용 접근
    security_constraints:
      - no_write_operations
      - review_target_only
    filter_overrides:
      min_changed_lines: 50
      
  - name: ecommerce-microservices
    path: /Users/demin_coder/Dev/ecommerce-microservices
    tech_stack: java_spring
    description: "java, spring, jpa로 구현된 MSA 서버 애플리케이션"
    filter_overrides:
      min_changed_lines: 100  # Java는 더 큰 단위 변경
      file_types: [".java", ".kt", ".xml"]
      
  - name: kotlin-realworld
    path: /Users/demin_coder/Dev/kotlin-realworld
    tech_stack: kotlin_jpa
    description: "java, kotlin, jpa로 구현된 호텔 예약 서버 애플리케이션"
    filter_overrides:
      min_changed_lines: 80
      file_types: [".kt", ".java"]

review_models:
  - "gemini-2.5-pro"
  - "claude-sonnet-4"
  - "claude-sonnet-4-thinking"

commit_filters:
  keywords:
    include: ["fix", "feature", "refactor", "improve", "add", "update"]
    exclude: ["typo", "format", "style", "docs", "chore"]
  stats:
    min_files: 2
    max_files: 10
    min_lines: 50
  merge_handling:
    fast_forward: exclude
    conflict_resolution: include
    squash_merge: include
    feature_branch: conditional  # 변경량 기준
commits_per_repo: 5

workflow:
  skip_existing:
    commit_filtering: true  # 필터링된 commit JSON 존재 시 skip
    review_results: true    # 동일 commit-model 조합 결과 존재 시 skip
  parallel_execution:
    max_concurrent_repos: 2
    max_concurrent_models: 3
  cache_enabled: true

# Selvage 실행 설정
selvage:
  binary_path: "/Users/demin_coder/.local/bin/selvage"
  timeout_seconds: 300
  
# DeepEval 설정
deepeval:
  metrics:
    - name: "Correctness"
      description: "리뷰의 정확성"
      threshold: 0.7
    - name: "Clarity" 
      description: "리뷰의 명확성"
      threshold: 0.6
    - name: "Actionability"
      description: "실행 가능성"
      threshold: 0.6
    - name: "JsonCorrectness"
      description: "JSON 형식 정확성"
      threshold: 0.8

# 보안 및 리소스 제한
security:
  allowed_paths:
    - "./selvage-eval-results/"
    - "/Users/demin_coder/Dev/cline"
    - "/Users/demin_coder/Dev/selvage-deprecated"
    - "/Users/demin_coder/Dev/ecommerce-microservices"
    - "/Users/demin_coder/Dev/kotlin-realworld"
  forbidden_commands:
    - "rm"
    - "rmdir"
    - "delete"
    - "chmod"
    - "chown"
    - "curl"
    - "wget"
    - "sudo"
    - "su"

resource_limits:
  max_memory_mb: 2048
  max_cpu_percent: 80
  max_disk_gb: 10
  max_execution_time: 3600  # 1시간

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/selvage-eval.log"